name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install build dependencies
      run: sudo apt-get install -y libsdl1.2-dev libsdl-gfx1.2-dev
    - name: Generate configure script
      run: autoreconf -i
    - name: Configure
      run: ./configure
    - name: Build
      run: make
    - name: Run Tests
      run: make check
    - name: Perform Distribution Check
      run: make distcheck
