name: Tetris Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout code
      
    - name: Install SDL2 dependencies
      run: sudo apt-get install -y libsdl2-dev libsdl2-gfx-dev
      
    - name: Build using Makefile
      run: make
      
    - name: Verify executable was created
      run: ls -la build/tetris